<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="keywords" content="app, responsive, jquery, bootstrap, dashboard, admin">
    <title><? $t->block('title') ?><? $this->end() ?></title>
    <? $t->block('css') ?><? $t->end() ?>
</head>
<body>
<? $t->block('content') ?><? $t->end() ?>
<? $t->block('modal') ?><? $t->end() ?>
<? $t->block('js') ?><? $t->end() ?>
</body>

</html>